# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PraiseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户昵称')),
                ('mobile', models.CharField(blank=True, max_length=24, null=True, verbose_name='用户电话')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别')),
                ('birthday', models.CharField(blank=True, max_length=24, null=True, verbose_name='生日')),
                ('country', models.CharField(blank=True, max_length=32, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=32, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='城市')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='积分')),
                ('contact_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='详细地址')),
                ('is_member', models.BooleanField(default=False, verbose_name='是否为有赞会员')),
                ('trade_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('yz_uid', models.IntegerField(blank=True, null=True, verbose_name='有赞id')),
            ],
            options={
                'verbose_name': '有赞用户表',
                'verbose_name_plural': '有赞用户表',
            },
        ),
    ]
