# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户昵称')),
                ('mobile', models.CharField(blank=True, max_length=24, null=True, verbose_name='用户电话')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别')),
            ],
        ),
    ]
